# Generated by Django 4.2.21 on 2025-06-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
