# Generated by Django 4.2.21 on 2025-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0005_document_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
