# Generated by Django 4.2.21 on 2025-06-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark', '0008_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='two_factor_enabled',
        ),
        migrations.AlterField(
            model_name='decrypteddocument',
            name='file',
            field=models.FileField(upload_to='decrypted/'),
        ),
        migrations.AlterField(
            model_name='decrypteddocument',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
